import '@/styles/globals.css'
import Head from 'next/head'
import { ThemeProvider } from "next-themes"
import Script from 'next/script'

export default function App({ Component, pageProps }) {
  return (
    <ThemeProvider defaultTheme="light" attribute="class">
      <Script src="https://unpkg.com/cursor-effects@latest/dist/browser.js"></Script>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </ThemeProvider>
  ) 
}
